package com.muyun.core.model.order;

import java.io.Serializable;

public class OrderSource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_order_source.s_id
     *
     * @mbggenerated
     */
    private String sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_order_source.s_name
     *
     * @mbggenerated
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_order_source.s_temp
     *
     * @mbggenerated
     */
    private String sTemp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunmu_order_source
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_order_source.s_id
     *
     * @return the value of yunmu_order_source.s_id
     *
     * @mbggenerated
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_order_source.s_id
     *
     * @param sId the value for yunmu_order_source.s_id
     *
     * @mbggenerated
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_order_source.s_name
     *
     * @return the value of yunmu_order_source.s_name
     *
     * @mbggenerated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_order_source.s_name
     *
     * @param sName the value for yunmu_order_source.s_name
     *
     * @mbggenerated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_order_source.s_temp
     *
     * @return the value of yunmu_order_source.s_temp
     *
     * @mbggenerated
     */
    public String getsTemp() {
        return sTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_order_source.s_temp
     *
     * @param sTemp the value for yunmu_order_source.s_temp
     *
     * @mbggenerated
     */
    public void setsTemp(String sTemp) {
        this.sTemp = sTemp == null ? null : sTemp.trim();
    }
}