package com.muyun.core.model.order;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class OrderExt implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column muyun_order.o_id
     *
     * @mbggenerated
     */
    private String oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column muyun_order.h_id
     *
     * @mbggenerated
     */
    private String hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column muyun_order.o_date
     *
     * @mbggenerated
     */
    private Date oDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column muyun_order.o_start_date
     *
     * @mbggenerated
     */
    private Date oStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column muyun_order.o_end_date
     *
     * @mbggenerated
     */
    private Date oEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column muyun_order.o_act_amount
     *
     * @mbggenerated
     */
    private Double oActAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column muyun_order.o_rec_amount
     *
     * @mbggenerated
     */
    private Double oRecAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column muyun_order.o_source
     *
     * @mbggenerated
     */
    private String oSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column muyun_order.o_status
     *
     * @mbggenerated
     */
    private Integer oStatus;

    private String payWay;
    private String sourceWay;

    public String getPayWay() {
        return payWay;
    }

    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }

    public String getSourceWay() {
        return sourceWay;
    }

    public void setSourceWay(String sourceWay) {
        this.sourceWay = sourceWay;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column muyun_order.o_way
     *
     * @mbggenerated
     */
    private Integer oWay;

    private String hNumber;

    private List<OrderItem> orderItems;

    public List<OrderItem> getOrderItems() {
        return orderItems;
    }

    public void setOrderItems(List<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }

    public String gethNumber() {
        return hNumber;
    }

    public void sethNumber(String hNumber) {
        this.hNumber = hNumber;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table muyun_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column muyun_order.o_id
     *
     * @return the value of muyun_order.o_id
     *
     * @mbggenerated
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column muyun_order.o_id
     *
     * @param oId the value for muyun_order.o_id
     *
     * @mbggenerated
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column muyun_order.h_id
     *
     * @return the value of muyun_order.h_id
     *
     * @mbggenerated
     */
    public String gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column muyun_order.h_id
     *
     * @param hId the value for muyun_order.h_id
     *
     * @mbggenerated
     */
    public void sethId(String hId) {
        this.hId = hId == null ? null : hId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column muyun_order.o_date
     *
     * @return the value of muyun_order.o_date
     *
     * @mbggenerated
     */
    public Date getoDate() {
        return oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column muyun_order.o_date
     *
     * @param oDate the value for muyun_order.o_date
     *
     * @mbggenerated
     */
    public void setoDate(Date oDate) {
        this.oDate = oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column muyun_order.o_start_date
     *
     * @return the value of muyun_order.o_start_date
     *
     * @mbggenerated
     */
    public Date getoStartDate() {
        return oStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column muyun_order.o_start_date
     *
     * @param oStartDate the value for muyun_order.o_start_date
     *
     * @mbggenerated
     */
    public void setoStartDate(Date oStartDate) {
        this.oStartDate = oStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column muyun_order.o_end_date
     *
     * @return the value of muyun_order.o_end_date
     *
     * @mbggenerated
     */
    public Date getoEndDate() {
        return oEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column muyun_order.o_end_date
     *
     * @param oEndDate the value for muyun_order.o_end_date
     *
     * @mbggenerated
     */
    public void setoEndDate(Date oEndDate) {
        this.oEndDate = oEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column muyun_order.o_act_amount
     *
     * @return the value of muyun_order.o_act_amount
     *
     * @mbggenerated
     */
    public Double getoActAmount() {
        return oActAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column muyun_order.o_act_amount
     *
     * @param oActAmount the value for muyun_order.o_act_amount
     *
     * @mbggenerated
     */
    public void setoActAmount(Double oActAmount) {
        this.oActAmount = oActAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column muyun_order.o_rec_amount
     *
     * @return the value of muyun_order.o_rec_amount
     *
     * @mbggenerated
     */
    public Double getoRecAmount() {
        return oRecAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column muyun_order.o_rec_amount
     *
     * @param oRecAmount the value for muyun_order.o_rec_amount
     *
     * @mbggenerated
     */
    public void setoRecAmount(Double oRecAmount) {
        this.oRecAmount = oRecAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column muyun_order.o_source
     *
     * @return the value of muyun_order.o_source
     *
     * @mbggenerated
     */
    public String getoSource() {
        return oSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column muyun_order.o_source
     *
     * @param oSource the value for muyun_order.o_source
     *
     * @mbggenerated
     */
    public void setoSource(String oSource) {
        this.oSource = oSource == null ? null : oSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column muyun_order.o_status
     *
     * @return the value of muyun_order.o_status
     *
     * @mbggenerated
     */
    public Integer getoStatus() {
        return oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column muyun_order.o_status
     *
     * @param oStatus the value for muyun_order.o_status
     *
     * @mbggenerated
     */
    public void setoStatus(Integer oStatus) {
        this.oStatus = oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column muyun_order.o_way
     *
     * @return the value of muyun_order.o_way
     *
     * @mbggenerated
     */
    public Integer getoWay() {
        return oWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column muyun_order.o_way
     *
     * @param oWay the value for muyun_order.o_way
     *
     * @mbggenerated
     */
    public void setoWay(Integer oWay) {
        this.oWay = oWay;
    }
}