package com.muyun.core.dao.order;

import com.muyun.core.model.order.PayWay;
import com.muyun.core.model.order.PayWayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayWayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    int countByExample(PayWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    int deleteByExample(PayWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    int insert(PayWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    int insertSelective(PayWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    List<PayWay> selectByExample(PayWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    PayWay selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PayWay record, @Param("example") PayWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PayWay record, @Param("example") PayWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_pay_way
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayWay record);

    List<PayWay> getPayWayAll();
}