package com.muyun.core.model.owner;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OwnerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public OwnerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andURelNameIsNull() {
            addCriterion("u_rel_name is null");
            return (Criteria) this;
        }

        public Criteria andURelNameIsNotNull() {
            addCriterion("u_rel_name is not null");
            return (Criteria) this;
        }

        public Criteria andURelNameEqualTo(String value) {
            addCriterion("u_rel_name =", value, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameNotEqualTo(String value) {
            addCriterion("u_rel_name <>", value, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameGreaterThan(String value) {
            addCriterion("u_rel_name >", value, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameGreaterThanOrEqualTo(String value) {
            addCriterion("u_rel_name >=", value, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameLessThan(String value) {
            addCriterion("u_rel_name <", value, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameLessThanOrEqualTo(String value) {
            addCriterion("u_rel_name <=", value, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameLike(String value) {
            addCriterion("u_rel_name like", value, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameNotLike(String value) {
            addCriterion("u_rel_name not like", value, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameIn(List<String> values) {
            addCriterion("u_rel_name in", values, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameNotIn(List<String> values) {
            addCriterion("u_rel_name not in", values, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameBetween(String value1, String value2) {
            addCriterion("u_rel_name between", value1, value2, "uRelName");
            return (Criteria) this;
        }

        public Criteria andURelNameNotBetween(String value1, String value2) {
            addCriterion("u_rel_name not between", value1, value2, "uRelName");
            return (Criteria) this;
        }

        public Criteria andUNameIsNull() {
            addCriterion("u_name is null");
            return (Criteria) this;
        }

        public Criteria andUNameIsNotNull() {
            addCriterion("u_name is not null");
            return (Criteria) this;
        }

        public Criteria andUNameEqualTo(String value) {
            addCriterion("u_name =", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotEqualTo(String value) {
            addCriterion("u_name <>", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameGreaterThan(String value) {
            addCriterion("u_name >", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameGreaterThanOrEqualTo(String value) {
            addCriterion("u_name >=", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLessThan(String value) {
            addCriterion("u_name <", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLessThanOrEqualTo(String value) {
            addCriterion("u_name <=", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLike(String value) {
            addCriterion("u_name like", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotLike(String value) {
            addCriterion("u_name not like", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameIn(List<String> values) {
            addCriterion("u_name in", values, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotIn(List<String> values) {
            addCriterion("u_name not in", values, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameBetween(String value1, String value2) {
            addCriterion("u_name between", value1, value2, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotBetween(String value1, String value2) {
            addCriterion("u_name not between", value1, value2, "uName");
            return (Criteria) this;
        }

        public Criteria andUPwdIsNull() {
            addCriterion("u_pwd is null");
            return (Criteria) this;
        }

        public Criteria andUPwdIsNotNull() {
            addCriterion("u_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andUPwdEqualTo(String value) {
            addCriterion("u_pwd =", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotEqualTo(String value) {
            addCriterion("u_pwd <>", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdGreaterThan(String value) {
            addCriterion("u_pwd >", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdGreaterThanOrEqualTo(String value) {
            addCriterion("u_pwd >=", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdLessThan(String value) {
            addCriterion("u_pwd <", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdLessThanOrEqualTo(String value) {
            addCriterion("u_pwd <=", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdLike(String value) {
            addCriterion("u_pwd like", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotLike(String value) {
            addCriterion("u_pwd not like", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdIn(List<String> values) {
            addCriterion("u_pwd in", values, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotIn(List<String> values) {
            addCriterion("u_pwd not in", values, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdBetween(String value1, String value2) {
            addCriterion("u_pwd between", value1, value2, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotBetween(String value1, String value2) {
            addCriterion("u_pwd not between", value1, value2, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUTelIsNull() {
            addCriterion("u_tel is null");
            return (Criteria) this;
        }

        public Criteria andUTelIsNotNull() {
            addCriterion("u_tel is not null");
            return (Criteria) this;
        }

        public Criteria andUTelEqualTo(String value) {
            addCriterion("u_tel =", value, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelNotEqualTo(String value) {
            addCriterion("u_tel <>", value, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelGreaterThan(String value) {
            addCriterion("u_tel >", value, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelGreaterThanOrEqualTo(String value) {
            addCriterion("u_tel >=", value, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelLessThan(String value) {
            addCriterion("u_tel <", value, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelLessThanOrEqualTo(String value) {
            addCriterion("u_tel <=", value, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelLike(String value) {
            addCriterion("u_tel like", value, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelNotLike(String value) {
            addCriterion("u_tel not like", value, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelIn(List<String> values) {
            addCriterion("u_tel in", values, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelNotIn(List<String> values) {
            addCriterion("u_tel not in", values, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelBetween(String value1, String value2) {
            addCriterion("u_tel between", value1, value2, "uTel");
            return (Criteria) this;
        }

        public Criteria andUTelNotBetween(String value1, String value2) {
            addCriterion("u_tel not between", value1, value2, "uTel");
            return (Criteria) this;
        }

        public Criteria andUAddrIsNull() {
            addCriterion("u_addr is null");
            return (Criteria) this;
        }

        public Criteria andUAddrIsNotNull() {
            addCriterion("u_addr is not null");
            return (Criteria) this;
        }

        public Criteria andUAddrEqualTo(String value) {
            addCriterion("u_addr =", value, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrNotEqualTo(String value) {
            addCriterion("u_addr <>", value, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrGreaterThan(String value) {
            addCriterion("u_addr >", value, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrGreaterThanOrEqualTo(String value) {
            addCriterion("u_addr >=", value, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrLessThan(String value) {
            addCriterion("u_addr <", value, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrLessThanOrEqualTo(String value) {
            addCriterion("u_addr <=", value, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrLike(String value) {
            addCriterion("u_addr like", value, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrNotLike(String value) {
            addCriterion("u_addr not like", value, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrIn(List<String> values) {
            addCriterion("u_addr in", values, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrNotIn(List<String> values) {
            addCriterion("u_addr not in", values, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrBetween(String value1, String value2) {
            addCriterion("u_addr between", value1, value2, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUAddrNotBetween(String value1, String value2) {
            addCriterion("u_addr not between", value1, value2, "uAddr");
            return (Criteria) this;
        }

        public Criteria andUDescIsNull() {
            addCriterion("u_desc is null");
            return (Criteria) this;
        }

        public Criteria andUDescIsNotNull() {
            addCriterion("u_desc is not null");
            return (Criteria) this;
        }

        public Criteria andUDescEqualTo(String value) {
            addCriterion("u_desc =", value, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescNotEqualTo(String value) {
            addCriterion("u_desc <>", value, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescGreaterThan(String value) {
            addCriterion("u_desc >", value, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescGreaterThanOrEqualTo(String value) {
            addCriterion("u_desc >=", value, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescLessThan(String value) {
            addCriterion("u_desc <", value, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescLessThanOrEqualTo(String value) {
            addCriterion("u_desc <=", value, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescLike(String value) {
            addCriterion("u_desc like", value, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescNotLike(String value) {
            addCriterion("u_desc not like", value, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescIn(List<String> values) {
            addCriterion("u_desc in", values, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescNotIn(List<String> values) {
            addCriterion("u_desc not in", values, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescBetween(String value1, String value2) {
            addCriterion("u_desc between", value1, value2, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDescNotBetween(String value1, String value2) {
            addCriterion("u_desc not between", value1, value2, "uDesc");
            return (Criteria) this;
        }

        public Criteria andUDateIsNull() {
            addCriterion("u_date is null");
            return (Criteria) this;
        }

        public Criteria andUDateIsNotNull() {
            addCriterion("u_date is not null");
            return (Criteria) this;
        }

        public Criteria andUDateEqualTo(Date value) {
            addCriterion("u_date =", value, "uDate");
            return (Criteria) this;
        }

        public Criteria andUDateNotEqualTo(Date value) {
            addCriterion("u_date <>", value, "uDate");
            return (Criteria) this;
        }

        public Criteria andUDateGreaterThan(Date value) {
            addCriterion("u_date >", value, "uDate");
            return (Criteria) this;
        }

        public Criteria andUDateGreaterThanOrEqualTo(Date value) {
            addCriterion("u_date >=", value, "uDate");
            return (Criteria) this;
        }

        public Criteria andUDateLessThan(Date value) {
            addCriterion("u_date <", value, "uDate");
            return (Criteria) this;
        }

        public Criteria andUDateLessThanOrEqualTo(Date value) {
            addCriterion("u_date <=", value, "uDate");
            return (Criteria) this;
        }

        public Criteria andUDateIn(List<Date> values) {
            addCriterion("u_date in", values, "uDate");
            return (Criteria) this;
        }

        public Criteria andUDateNotIn(List<Date> values) {
            addCriterion("u_date not in", values, "uDate");
            return (Criteria) this;
        }

        public Criteria andUDateBetween(Date value1, Date value2) {
            addCriterion("u_date between", value1, value2, "uDate");
            return (Criteria) this;
        }

        public Criteria andUDateNotBetween(Date value1, Date value2) {
            addCriterion("u_date not between", value1, value2, "uDate");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(Integer value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(Integer value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(Integer value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(Integer value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(Integer value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(Integer value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<Integer> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<Integer> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(Integer value1, Integer value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(Integer value1, Integer value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andUEmailIsNull() {
            addCriterion("u_email is null");
            return (Criteria) this;
        }

        public Criteria andUEmailIsNotNull() {
            addCriterion("u_email is not null");
            return (Criteria) this;
        }

        public Criteria andUEmailEqualTo(String value) {
            addCriterion("u_email =", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotEqualTo(String value) {
            addCriterion("u_email <>", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailGreaterThan(String value) {
            addCriterion("u_email >", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailGreaterThanOrEqualTo(String value) {
            addCriterion("u_email >=", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLessThan(String value) {
            addCriterion("u_email <", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLessThanOrEqualTo(String value) {
            addCriterion("u_email <=", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLike(String value) {
            addCriterion("u_email like", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotLike(String value) {
            addCriterion("u_email not like", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailIn(List<String> values) {
            addCriterion("u_email in", values, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotIn(List<String> values) {
            addCriterion("u_email not in", values, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailBetween(String value1, String value2) {
            addCriterion("u_email between", value1, value2, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotBetween(String value1, String value2) {
            addCriterion("u_email not between", value1, value2, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUStatusIsNull() {
            addCriterion("u_status is null");
            return (Criteria) this;
        }

        public Criteria andUStatusIsNotNull() {
            addCriterion("u_status is not null");
            return (Criteria) this;
        }

        public Criteria andUStatusEqualTo(Integer value) {
            addCriterion("u_status =", value, "uStatus");
            return (Criteria) this;
        }

        public Criteria andUStatusNotEqualTo(Integer value) {
            addCriterion("u_status <>", value, "uStatus");
            return (Criteria) this;
        }

        public Criteria andUStatusGreaterThan(Integer value) {
            addCriterion("u_status >", value, "uStatus");
            return (Criteria) this;
        }

        public Criteria andUStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("u_status >=", value, "uStatus");
            return (Criteria) this;
        }

        public Criteria andUStatusLessThan(Integer value) {
            addCriterion("u_status <", value, "uStatus");
            return (Criteria) this;
        }

        public Criteria andUStatusLessThanOrEqualTo(Integer value) {
            addCriterion("u_status <=", value, "uStatus");
            return (Criteria) this;
        }

        public Criteria andUStatusIn(List<Integer> values) {
            addCriterion("u_status in", values, "uStatus");
            return (Criteria) this;
        }

        public Criteria andUStatusNotIn(List<Integer> values) {
            addCriterion("u_status not in", values, "uStatus");
            return (Criteria) this;
        }

        public Criteria andUStatusBetween(Integer value1, Integer value2) {
            addCriterion("u_status between", value1, value2, "uStatus");
            return (Criteria) this;
        }

        public Criteria andUStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("u_status not between", value1, value2, "uStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myun_owner
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myun_owner
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}